### ISSUE TITLE
Can you make peerDependencies in package.json to "react": "^16.14.0"

### ISSUE THREAD

**Issue by liheng-zhang** [spaceymonk/react-radial-menu#4]
Our application is currently unable to upgrade to React 18.2. However, we have conducted tests and confirmed that it works without issues on React 16. Could you please allow for a wider range of React versions, including React 16?

**Comment by spaceymonk** [comment]
Solved: https://github.com/spaceymonk/react-radial-menu/releases/tag/v2.0.6
